In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt



In [ ]:
df = pd.read_csv("/content/titan_train.csv")

In [ ]:
df.shape

(891, 12)

#### identifying missing values

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### Data cleaning 

In [ ]:
df_col = ["Name","Ticket","Cabin","PassengerId","Embarked"]
df.drop(df_col,axis=1,inplace=True)

In [ ]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [ ]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [ ]:
df["Age"]=df['Age'].fillna(0)

#### Converting categorical data to numeric

In [ ]:
df = pd.get_dummies(df)

In [ ]:
df.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male
0         0       3  22.0      1      0   7.2500           0         1
1         1       1  38.0      1      0  71.2833           1         0
2         1       3  26.0      0      0   7.9250           1         0
3         1       1  35.0      1      0  53.1000           1         0
4         0       3  35.0      0      0   8.0500           0         1

In [ ]:
x = df.drop("Survived",axis=1)
y = df["Survived"]

#### Scaling transformation

In [ ]:
x_scaled = StandardScaler().fit_transform(x)
x_scaled

array([[ 0.82737724, -0.10231279,  0.43279337, ..., -0.50244517,
        -0.73769513,  0.73769513],
       [-1.56610693,  0.80749164,  0.43279337, ...,  0.78684529,
         1.35557354, -1.35557354],
       [ 0.82737724,  0.12513832, -0.4745452 , ..., -0.48885426,
         1.35557354, -1.35557354],
       ...,
       [ 0.82737724, -1.35329389,  0.43279337, ..., -0.17626324,
         1.35557354, -1.35557354],
       [-1.56610693,  0.12513832, -0.4745452 , ..., -0.04438104,
        -0.73769513,  0.73769513],
       [ 0.82737724,  0.46631498, -0.4745452 , ..., -0.49237783,
        -0.73769513,  0.73769513]])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x_scaled,y,test_size=.2)

In [ ]:
#finding optimal value for k

params = {"n_neighbors":range(1,51)}

In [ ]:
g_mod=GridSearchCV(KNeighborsClassifier(),params)

In [ ]:
g_mod.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 51)})

In [ ]:
g_mod.best_params_

{'n_neighbors': 9}

In [ ]:
#apply KNN model

model1 = KNeighborsClassifier(n_neighbors=9).fit(X_train,y_train)

In [ ]:
#prediction
p = model1.predict(X_test)
p

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0])

In [ ]:
confusion_matrix(y_test,p)

array([[97, 10],
       [20, 52]])

In [ ]:
accuracy_score(y_test,p)

0.8324022346368715

### Apply PCA

In [ ]:
pca = PCA(n_components=0.95)

In [ ]:
pca_scaled_x = pca.fit_transform(x_scaled)

In [ ]:
pca.explained_variance_ratio_

array([0.33491175, 0.23711703, 0.18467463, 0.11202034, 0.07889448,
       0.05238177])

In [ ]:
pca.n_components_

6

In [ ]:
#apply KNN model

model2 = KNeighborsClassifier(n_neighbors=6).fit(X_train,y_train)

In [ ]:
#prediction

p1 = model2.predict(X_test)

y_test

15     1
519    0
792    0
447    1
888    0
      ..
642    0
641    1
47     1
371    0
231    0
Name: Survived, Length: 179, dtype: int64

In [ ]:
p1

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0])

In [ ]:
accuracy_score(y_test,p1)

0.8212290502793296